"""
train_model.py - build a synthetic ECG dataset, train a small neural network (MLP)
and export it as firmware/esp32_ecg_monitor/model_weights.h

    pip install numpy scikit-learn
    python train_model.py                      # ~15k windows, a few minutes
    python train_model.py --per-class 3000     # bigger / more accurate

The model input is the 165-value feature vector from ecg_sim.extract_features(),
which the ESP32 recomputes with the identical algorithm (ecg_ml.h).
"""
import argparse, os, sys, time
import numpy as np
from multiprocessing import Pool
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

import ecg_sim as E

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, '..', 'firmware', 'esp32_ecg_monitor', 'model_weights.h')


def random_patient(rng):
    if rng.random() < 0.5:
        age = float(np.exp(rng.uniform(np.log(0.03), np.log(18))))
    else:
        age = float(rng.uniform(18, 95))
    th, tw = E.typical_for(age)
    h = float(np.clip(th * rng.uniform(0.9, 1.1), 40, 230))
    w = float(np.clip(tw * rng.uniform(0.9, 1.1) * rng.uniform(0.75, 1.35), 2, 250))
    return round(age, 2), round(h), round(w, 1)


def make_one(args):
    dx_idx, seed, jitter = args
    rng = np.random.default_rng(seed)
    age, h, w = random_patient(rng)
    x250, _, _ = E.simulate(E.DX_IDS[dx_idx], age, h, w, dur=6.0, fs=250, rng=rng,
                            noise=rng.random() < 0.85, jitter=jitter)
    x125 = E.decimate2(x250)
    return E.extract_features(x125, age, h, w), dx_idx


def build(n_per_class, seed0, jitter, procs):
    jobs = [(c, seed0 + c * 1_000_003 + i, jitter) for c in range(10) for i in range(n_per_class)]
    with Pool(procs) as p:
        res = p.map(make_one, jobs, chunksize=64)
    X = np.stack([r[0] for r in res]).astype(np.float32)
    y = np.array([r[1] for r in res])
    return X, y


def fmt(arr, per_line=8):
    a = np.asarray(arr, dtype=np.float32).ravel()
    lines = []
    for i in range(0, len(a), per_line):
        lines.append('  ' + ', '.join('%.7gf' % v for v in a[i:i + per_line]))
    return ',\n'.join(lines)


def export_header(path, mean, std, clf, acc):
    Ws, Bs = clf.coefs_, clf.intercepts_
    assert len(Ws) == 3, 'firmware expects exactly two hidden layers'
    dims = [Ws[0].shape[0], Ws[0].shape[1], Ws[1].shape[1], Ws[2].shape[1]]
    with open(path, 'w') as f:
        f.write('// AUTO-GENERATED by python/train_model.py  -  do not edit by hand.\n')
        f.write('// Held-out accuracy on synthetic data: %.2f%%\n#pragma once\n\n' % (100 * acc))
        f.write('#define MODEL_N_IN  %d\n#define MODEL_N_H1  %d\n#define MODEL_N_H2  %d\n#define MODEL_N_OUT %d\n\n' % tuple(dims))
        f.write('static const float MODEL_MEAN[MODEL_N_IN] = {\n%s\n};\n\n' % fmt(mean))
        f.write('static const float MODEL_STD[MODEL_N_IN] = {\n%s\n};\n\n' % fmt(std))
        for i, (W, b) in enumerate(zip(Ws, Bs), start=1):
            f.write('// layer %d weights, row-major [in][out]\n' % i)
            f.write('static const float MODEL_W%d[%d] = {\n%s\n};\n' % (i, W.size, fmt(W)))
            f.write('static const float MODEL_B%d[%d] = {\n%s\n};\n\n' % (i, b.size, fmt(b)))
    print('wrote', os.path.normpath(path))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--per-class', type=int, default=1500)
    ap.add_argument('--seed', type=int, default=42)
    ap.add_argument('--procs', type=int, default=os.cpu_count() or 1)
    ap.add_argument('--hidden', type=int, nargs=2, default=[64, 32])
    a = ap.parse_args()

    t = time.time()
    print('generating training windows ...')
    X, y = build(a.per_class, a.seed, True, a.procs)
    print('generating clean validation windows (exactly what the web app sends) ...')
    Xv, yv = build(max(100, a.per_class // 6), a.seed + 777, False, a.procs)
    print('  %.0f s' % (time.time() - t))

    mean = X.mean(0)
    std = X.std(0)
    std[std < 1e-6] = 1.0
    Xn, Xvn = (X - mean) / std, (Xv - mean) / std

    clf = MLPClassifier(hidden_layer_sizes=tuple(a.hidden), activation='relu', alpha=1e-4,
                        batch_size=128, learning_rate_init=2e-3, max_iter=200, early_stopping=True,
                        validation_fraction=0.12, n_iter_no_change=12, random_state=1, verbose=False)
    print('training ...')
    clf.fit(Xn, y)
    acc_train = clf.score(Xn, y)
    acc = clf.score(Xvn, yv)
    print('train acc %.4f | clean-validation acc %.4f' % (acc_train, acc))
    cm = confusion_matrix(yv, clf.predict(Xvn))
    print('rows = true, cols = predicted')
    print('      ' + ' '.join('%5s' % s[:5] for s in E.DX_IDS))
    for i, row in enumerate(cm):
        print('%-6s' % E.DX_IDS[i] + ' '.join('%5d' % v for v in row))

    export_header(OUT_H, mean, std, clf, acc)
    np.savez_compressed(os.path.join(HERE, 'val_set.npz'), X=Xv[:300], y=yv[:300])


if __name__ == '__main__':
    main()
